version: '2.2'

services:
  fakesmtp:
    image: gessnerfl/fake-smtp-server:latest
    container_name: fakesmtp
    hostname: fakesmtp
    ports:
      - "5080:5080"
      - "5081:5081"
      - "5025:5025"
